// Dutch translations. Keys are the English text used in the code.
// Anything missing here simply shows in English.

export default {
  // App shell and tabs (kept short so they fit under the icons)
  'Almost there': 'Bijna klaar',
  'Loading…': 'Laden…',
  'Loading your trips…': 'Je reizen worden geladen…',
  'Couldn’t load trips': 'Reizen konden niet worden geladen',
  'Check that the Firestore security rules from the setup guide have been published.': 'Controleer of de Firestore-beveiligingsregels uit de installatiehandleiding zijn gepubliceerd.',
  'Today': 'Vandaag',
  'Itinerary': 'Reisplan',
  'Reminders': 'Reminders',
  'Wishlist': 'Wensen',
  'Packing': 'Inpakken',
  'Expenses': 'Uitgaven',
  'Couldn’t save: {error}': 'Opslaan mislukt: {error}',
  'Main': 'Hoofdmenu',
  '1 needs attention': '1 vraagt aandacht',
  '{n} need attention': '{n} vragen aandacht',

  // Attachments and files
  'That file could not be loaded. Check your connection.': 'Dit bestand kon niet worden geladen. Controleer je verbinding.',
  'Remove {name}': '{name} verwijderen',
  '{name} (saved with the expense)': '{name} (wordt bij de uitgave opgeslagen)',
  'Uploading…': 'Uploaden…',
  'Add ticket or photo': 'Ticket of foto toevoegen',
  'Close preview': 'Voorbeeld sluiten',
  'Attachment': 'Bijlage',
  'Close': 'Sluiten',
  'Type': 'Soort',
  'Tap again to delete': 'Tik nogmaals om te verwijderen',
  'Delete': 'Verwijderen',
  'Could not read the file': 'Het bestand kon niet worden gelezen',
  'That file is too big. PDFs need to be under about 700 KB.': 'Dit bestand is te groot. Pdf’s mogen ongeveer 700 KB zijn.',
  'Could not read that image': 'Deze afbeelding kon niet worden gelezen',

  // Calendar export
  'Stay: {name}': 'Verblijf: {name}',
  'Booking ref: {ref}': 'Boekingsnummer: {ref}',

  // Stays band, days and times
  'Check out {name} by {time}': 'Uitchecken bij {name} voor {time}',
  'Check out {name}': 'Uitchecken bij {name}',
  '{name} from {time}': '{name} vanaf {time}',
  'Check in at {name} from {time}': 'Inchecken bij {name} vanaf {time}',
  'Check in at {name}': 'Inchecken bij {name}',
  'Staying at {name}': 'Overnachting in {name}',
  'No stay added for tonight': 'Nog geen overnachting voor vannacht',
  'Day {n}': 'Dag {n}',
  '{from} to {to}': '{from} t/m {to}',
  'All day': 'Hele dag',
  'No cost added': 'Geen kosten ingevuld',
  'not split': 'niet gedeeld',
  'split equally': 'eerlijk gedeeld',
  'paid by {name}': 'betaald door {name}',

  // Types, reminder kinds and categories
  'Flight': 'Vlucht',
  'Stay': 'Verblijf',
  'Activity': 'Activiteit',
  'Food': 'Eten',
  'Transport': 'Vervoer',
  'Boat': 'Boot',
  'Cancel': 'Annuleren',
  'Pay': 'Betalen',
  'Check in': 'Inchecken',
  'Confirm': 'Bevestigen',
  'Other': 'Overig',
  'Stays': 'Verblijven',
  'Flights': 'Vluchten',
  'Activities': 'Activiteiten',
  'Both': 'Allebei',
  'Shared': 'Samen',

  // Expenses
  'All square': 'Alles is verrekend',
  '{a} owes {b} {amount}': '{a} moet {b} nog {amount}',
  'Settled up: {a} paid {b}': 'Verrekend: {a} heeft {b} betaald',
  'Settled up': 'Verrekend',
  'Trip total': 'Totaal voor de reis',
  '{a} spent so far': '{a} tot nu toe uitgegeven',
  '{a} still to come': '{a} nog te gaan',
  'Spending by category': 'Uitgaven per categorie',
  'Balance': 'Saldo',
  '{name} paid {amount}': '{name} betaalde {amount}',
  'Settle up': 'Verrekenen',
  'Filter expenses': 'Uitgaven filteren',
  'Add a price when you put something on the itinerary and it shows up here. Anything else, add with the + button.': 'Vul een prijs in als je iets aan het reisplan toevoegt, dan komt het hier te staan. Al het andere voeg je toe met de +-knop.',
  'Before the trip': 'Voor de reis',
  'After the trip': 'Na de reis',
  'Payment between you': 'Betaling tussen jullie',
  'Paid by {name}': 'Betaald door {name}',
  'from itinerary': 'uit het reisplan',
  'added manually': 'zelf toegevoegd',
  'receipt': 'bonnetje',
  'planned': 'gepland',
  'Add an expense': 'Uitgave toevoegen',
  'All': 'Alles',
  'From itinerary': 'Uit het reisplan',
  'Added manually': 'Zelf toegevoegd',

  // Itinerary
  'Times in local time': 'Tijden in lokale tijd',
  'Days': 'Dagen',
  'today': 'vandaag',
  'Previous day': 'Vorige dag',
  'Next day': 'Volgende dag',
  '1 plan': '1 plan',
  '{n} plans': '{n} plannen',
  'Nothing planned yet': 'Nog niets gepland',
  'Add something at {time}': 'Iets toevoegen om {time}',
  'Add to this day': 'Aan deze dag toevoegen',

  // Login
  'Something went wrong ({code}).': 'Er ging iets mis ({code}).',
  'That email and password don’t match.': 'Dit e-mailadres en wachtwoord horen niet bij elkaar.',
  'That doesn’t look like an email address.': 'Dat lijkt geen e-mailadres.',
  'This account has been switched off.': 'Dit account is uitgeschakeld.',
  'Too many attempts. Wait a minute and try again.': 'Te veel pogingen. Wacht even en probeer het opnieuw.',
  'No connection. Try again when you have signal.': 'Geen verbinding. Probeer het opnieuw als je bereik hebt.',
  'Type your email first, then tap this again.': 'Vul eerst je e-mailadres in en tik hier dan nog een keer op.',
  'Check your inbox for a link to set a new password.': 'Kijk in je inbox voor een link om een nieuw wachtwoord in te stellen.',
  'Welcome back': 'Welkom terug',
  'Sign in to see your trip. Everything you add syncs to both your phones.': 'Log in om je reis te zien. Alles wat je toevoegt, staat meteen op jullie allebei je telefoon.',
  'Email': 'E-mailadres',
  'Password': 'Wachtwoord',
  'Signing in…': 'Inloggen…',
  'Sign in': 'Inloggen',
  'Forgot password': 'Wachtwoord vergeten',

  // Packing
  'Everyone': 'Iedereen',
  'Template added': 'Standaardlijst toegevoegd',
  '{a} of {b} packed': '{a} van {b} ingepakt',
  'Packing progress': 'Voortgang inpakken',
  'Whose items': 'Van wie',
  'New packing item': 'Nieuw item om in te pakken',
  'Add something to pack': 'Iets toevoegen om in te pakken',
  'Add item': 'Toevoegen',
  'Category': 'Categorie',
  'Whose item': 'Van wie',
  'Your list is empty. Start from a tropical trip template and tweak it, or add things one by one.': 'Je lijst is nog leeg. Begin met een standaardlijst voor een tropische reis en pas die aan, of voeg alles zelf toe.',
  'Use the tropical template': 'Tropische standaardlijst gebruiken',
  'Documents': 'Documenten',
  'Clothes': 'Kleding',
  'Toiletries': 'Toilettas',
  'Health': 'Gezondheid',
  'Electronics': 'Elektronica',
  'Beach': 'Strand',
  'Extras': 'Extra’s',

  // Reminders
  'Overdue': 'Verlopen',
  'Coming up': 'Binnenkort',
  'Done': 'Klaar',
  '{a} to do · {b} done': '{a} te doen · {b} klaar',
  'Things you mustn’t forget: bookings to cancel, balances to pay, online check-ins. Tap + to add one, or use "Add reminder" on any booking.': 'Dingen die je niet mag vergeten: boekingen annuleren, restbedragen betalen, online inchecken. Tik op + om er een toe te voegen, of gebruik "Reminder toevoegen" bij een boeking.',
  'No date': 'Geen datum',
  'For both of you': 'Voor jullie allebei',
  'For {name}': 'Voor {name}',
  'Linked to {name}': 'Gekoppeld aan {name}',
  'Mark not done: {name}': 'Markeer als niet klaar: {name}',
  'Mark done: {name}': 'Markeer als klaar: {name}',
  'Edit reminder: {name}': 'Reminder bewerken: {name}',
  'Add a reminder': 'Reminder toevoegen',

  // Today
  'in {time}': 'over {time}',
  'h': 'u',
  '{n} overdue': '{n} verlopen',
  '{n} due today': '{n} vandaag',
  'Day {n} of {total}': 'Dag {n} van {total}',
  '1 day to go': 'nog 1 dag',
  '{n} days to go': 'nog {n} dagen',
  'trip complete': 'reis afgerond',
  'Day 1: {date}': 'Dag 1: {date}',
  '{time} local time': '{time} lokale tijd',
  'Here’s what’s planned for your first day.': 'Dit staat er gepland voor je eerste dag.',
  'Settings': 'Instellingen',
  'Reminders: {list}': 'Reminders: {list}',
  'Happening now': 'Nu bezig',
  'until {time}': 'tot {time}',
  'Next up': 'Hierna',
  'First up': 'Als eerste',
  'Directions': 'Route',
  'Details': 'Details',
  'That’s a wrap. Have a look at Expenses for the final totals.': 'Dat was het! Kijk bij Uitgaven voor de eindtotalen.',
  'Nothing else planned for today.': 'Verder niets gepland voor vandaag.',
  'Add something': 'Iets toevoegen',
  'Later today': 'Later vandaag',
  'Tonight': 'Vannacht',
  'Directions to tonight’s stay': 'Route naar de overnachting van vannacht',
  'No stay added for tonight. Tap to add one.': 'Nog geen overnachting voor vannacht. Tik om er een toe te voegen.',

  // Trip setup and settings
  'Check the dates: the last day has to be on or after the first day.': 'Controleer de datums: de laatste dag moet op of na de eerste dag vallen.',
  'Add a rate for each extra currency, or remove it.': 'Vul voor elke extra valuta een koers in, of verwijder hem.',
  'Trip': 'Reis',
  'Trip name': 'Naam van de reis',
  'First day': 'Eerste dag',
  'Last day': 'Laatste dag',
  'Time zone for the itinerary': 'Tijdzone voor het reisplan',
  'Local money': 'Lokale valuta',
  'Home money': 'Eigen valuta',
  'Other currencies on this trip (e.g. VND for a few days in Vietnam)': 'Andere valuta op deze reis (bijv. VND voor een paar dagen Vietnam)',
  'Currency': 'Valuta',
  'Rate for {code}': 'Koers voor {code}',
  'Rate': 'Koers',
  'Add a currency': 'Valuta toevoegen',
  'Your name': 'Jouw naam',
  'e.g. Sam': 'bijv. Sam',
  'Partner’s name': 'Naam van je partner',
  'e.g. Alex': 'bijv. Alex',
  'Partner’s email (their login)': 'E-mailadres van je partner (om in te loggen)',
  'So they can see and edit the trip': 'Zodat die de reis kan zien en bewerken',
  'First things first': 'Eerst even dit',
  'New trip': 'Nieuwe reis',
  'Set up your trip': 'Stel je reis in',
  'You can change all of this later in Settings.': 'Je kunt dit later allemaal aanpassen bij Instellingen.',
  'Create trip': 'Reis aanmaken',
  'Thailand / Vietnam (UTC+7)': 'Thailand / Vietnam (UTC+7)',
  'Netherlands': 'Nederland',
  'United Kingdom': 'Verenigd Koninkrijk',
  'Singapore / Malaysia': 'Singapore / Maleisië',
  'Vietnam': 'Vietnam',
  'Bali': 'Bali',
  'Japan': 'Japan',
  'Sydney': 'Sydney',
  'New York': 'New York',
  'Los Angeles': 'Los Angeles',

  // Wishlist
  '1 idea': '1 idee',
  '{n} ideas': '{n} ideeën',
  '{n} on the itinerary': '{n} in het reisplan',
  'Filter by area': 'Filter op plek',
  'Collect places you might want to go. When you decide, tap "Add to a day" and it lands on the itinerary.': 'Verzamel plekken waar je misschien heen wilt. Heb je besloten? Tik op "Inplannen" en het staat in het reisplan.',
  'free': 'gratis',
  'about {amount}': 'ongeveer {amount}',
  'Edit {name}': '{name} bewerken',
  '{name} is keen': '{name} wil graag',
  '{name} is not keen yet': '{name} twijfelt nog',
  'Add to a day': 'Inplannen',
  'Add a wishlist idea': 'Idee toevoegen',
  'Added to the wishlist': 'Toegevoegd aan de wensen',
  'Wishlist idea': 'Idee',
  'Edit idea': 'Idee bewerken',
  'New idea': 'Nieuw idee',
  'e.g. Sunrise at Wat Arun': 'bijv. Zonsopkomst bij Wat Arun',
  'e.g. Bangkok': 'bijv. Bangkok',
  'Rough cost': 'Geschatte kosten',
  'Note': 'Notitie',
  'Why it\'s worth it, opening times…': 'Waarom het de moeite waard is, openingstijden…',
  'Save to wishlist': 'Opslaan bij de wensen',
  'On the itinerary': 'Staat in het reisplan',
  'Add to the itinerary': 'Aan het reisplan toevoegen',
  'Which day': 'Welke dag',
  'Add to {day}': 'Toevoegen aan {day}',

  // Expense form
  'Saved': 'Opgeslagen',
  'Expense added': 'Uitgave toegevoegd',
  'Expense': 'Uitgave',
  'Edit expense': 'Uitgave bewerken',
  'A payment between the two of you': 'Een betaling tussen jullie tweeën',
  'For anything paid outside the itinerary': 'Voor alles wat je buiten het reisplan om betaalt',
  'What was it': 'Wat was het',
  'e.g. Taxi from the pier': 'bijv. Taxi vanaf de pier',
  'Amount': 'Bedrag',
  'When (empty = before the trip)': 'Wanneer (leeg = voor de reis)',
  'Paid by': 'Betaald door',
  'Split': 'Verdelen',
  'Split equally': 'Eerlijk delen',
  'Just the payer': 'Alleen de betaler',
  'Attach a receipt photo': 'Foto van bonnetje toevoegen',
  'Save expense': 'Uitgave opslaan',

  // Item detail and form
  'Copied': 'Gekopieerd',
  'Couldn’t copy': 'Kopiëren lukte niet',
  'added by {name}': 'toegevoegd door {name}',
  'When': 'Wanneer',
  'check-in from {time}': 'inchecken vanaf {time}',
  'check-out by {time}': 'uitchecken voor {time}',
  'Where': 'Waar',
  'Cost': 'Kosten',
  'Booking reference': 'Boekingsnummer',
  'Copy': 'Kopiëren',
  'Notes': 'Notities',
  'Add reminder': 'Reminder toevoegen',
  'Edit': 'Bewerken',
  'Directions in Google Maps': 'Route in Google Maps',
  'Added, and the cost is in Expenses': 'Toegevoegd, en de kosten staan bij Uitgaven',
  'Added': 'Toegevoegd',
  'Deleted': 'Verwijderd',
  'Add to the day': 'Aan de dag toevoegen',
  'Add a stay': 'Overnachting toevoegen',
  'Shows as the hotel band on each night': 'Staat als hotelbalk bij elke nacht',
  'Hotel or place name': 'Hotel of naam van de plek',
  'What': 'Wat',
  'e.g. Riverside hotel': 'bijv. Riverside hotel',
  'e.g. Sunset at the pier': 'bijv. Zonsondergang bij de pier',
  'Check out': 'Uitchecken',
  'Check-in from': 'Inchecken vanaf',
  'Check-out by': 'Uitchecken voor',
  'Day': 'Dag',
  'Set times': 'Met tijden',
  'Timing': 'Tijd',
  'From': 'Van',
  'To': 'Tot',
  'Where (used for directions)': 'Waar (voor de route)',
  'Place name or address': 'Naam van de plek of adres',
  'Price': 'Prijs',
  'Optional': 'Optioneel',
  'Save changes': 'Wijzigingen opslaan',
  'Add': 'Toevoegen',

  // Reminder form
  'Reminder added': 'Reminder toegevoegd',
  'Reminder': 'Reminder',
  'Edit reminder': 'Reminder bewerken',
  'New reminder': 'Nieuwe reminder',
  'Not linked to a booking': 'Niet gekoppeld aan een boeking',
  'Kind of reminder': 'Soort reminder',
  'What needs doing': 'Wat moet er gebeuren',
  'e.g. Cancel the backup hotel': 'bijv. Het reservehotel annuleren',
  'Do it by': 'Uiterlijk',
  'Time': 'Tijd',
  'Who’s on it': 'Wie regelt het',
  'Linked booking (optional)': 'Gekoppelde boeking (optioneel)',
  'None': 'Geen',
  'Note (optional)': 'Notitie (optioneel)',
  'e.g. Free cancellation until then': 'bijv. Tot dan gratis annuleren',
  'Save reminder': 'Reminder opslaan',

  // Settings
  'Signed in as {email}': 'Ingelogd als {email}',
  'Language': 'Taal',
  'Calendar': 'Agenda',
  'Download the itinerary as a calendar file, then open it (or import it at calendar.google.com, Settings, Import). Re-export after big changes.': 'Download het reisplan als agendabestand en open het (of importeer het via calendar.google.com, Instellingen, Importeren). Exporteer opnieuw na grote wijzigingen.',
  'Calendar file downloaded': 'Agendabestand gedownload',
  'Export to Google Calendar (.ics)': 'Exporteren naar Google Agenda (.ics)',
  'Your trips': 'Jullie reizen',
  'This trip': 'Deze reis',
  'Save trip settings': 'Reisinstellingen opslaan',
  'Plan another trip': 'Nog een reis plannen',
  'Sign out': 'Uitloggen',
  // Journeys across days and time zones
  'It arrives before it departs. Check the days, times and time zones.': 'De aankomst ligt voor het vertrek. Controleer de dagen, tijden en tijdzones.',
  'Ends the next day': 'Eindigt de volgende dag',
  'Departs': 'Vertrek',
  'Departure time': 'Vertrektijd',
  'Time zone': 'Tijdzone',
  'Arrives': 'Aankomst',
  'Arrival time': 'Aankomsttijd',
  'Time zone on arrival': 'Tijdzone bij aankomst',
  'Journey time: {time}': 'Reistijd: {time}',
  '{time} → {day}': '{time} → {day}',
  'arrives {time}': 'aankomst {time}',
  'continues': 'onderweg',
  'your own rate': 'eigen koers',
  'looking up the rate…': 'koers opzoeken…',
  'rate of {date}': 'koers van {date}',
  'offline: trip rate used': 'offline: reiskoers gebruikt',
  'Exchange rate': 'Wisselkoers',
  'Paid': 'Betaald',
  'Still to pay': 'Nog te betalen',
  'To pay': 'Te betalen',
  '{a} paid': '{a} betaald',
  '{a} still to pay': '{a} nog te betalen',
  '{name} pays': '{name} betaalt',
  'still to pay by {name}': 'nog te betalen door {name}',
  'Mark as paid': 'Markeer als betaald',
  'Marked as paid': 'Gemarkeerd als betaald',
  'Rates follow the daily exchange rate automatically. Each price keeps the rate of the day it was paid.': 'Koersen volgen automatisch de dagkoers. Elke prijs houdt de koers van de dag waarop hij betaald is.',
  'Lists': 'Lijstjes',
  'Show the driver': 'Toon aan chauffeur',
  'Show this to your driver': 'Laat dit aan je chauffeur zien',
  'Looking up the local address…': 'Lokaal adres opzoeken…',
  'Your own text': 'Je eigen tekst',
  'Address from OpenStreetMap': 'Adres van OpenStreetMap',
  'Name machine-translated, area from OpenStreetMap': 'Naam automatisch vertaald, omgeving van OpenStreetMap',
  'Machine-translated: check it looks right': 'Automatisch vertaald: controleer of het klopt',
  'Add a place or address to this item first.': 'Voeg eerst een plaats of adres toe aan dit onderdeel.',
  'Couldn’t find a local address (no internet, or the place isn’t on the map). You can paste one yourself, e.g. from the booking confirmation or Google Maps.': 'Geen lokaal adres gevonden (geen internet, of de plek staat niet op de kaart). Je kunt er zelf een plakken, bijvoorbeeld uit de boekingsbevestiging of Google Maps.',
  'Address in the local language (paste from the booking or Google Maps)': 'Adres in de lokale taal (plak uit de boeking of Google Maps)',
  'Paste an address': 'Adres plakken',
  'Look up again': 'Opnieuw opzoeken',
  'Maps': 'Kaart',
  'Save': 'Opslaan',
};
